
name: test-ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: trapajim/go-pipeline-action@v1
        with:
          go-version: '1.22.2'
          go-vet: true
          golangci-version: latest
          go-test-flags: './... -v'